[package]
name = "egor00f/tablelib"

description = "Library for create GUI tables"

version = "0.2.0"

registry = "https://github.com/UpliftGames/wally-index"

license = "MIT"

realm = "shared"

repository = "https://github.com/Ukuroks-games/TableLib"

homepage = "https://ukuroks-games.github.io/TableLib/"

exclude = [
	"TableLib.rbxl", 
	"TableLib.project.json", 
	"examples", 
	"lua2dox",
	"Docs/Doxyfile", 
	"Docs/html"
]
